# Generated by Django 6.0.3 on 2026-04-02 18:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScannedSpecimen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(max_length=200)),
                ('scientific_name', models.CharField(blank=True, max_length=200)),
                ('confidence', models.FloatField(default=0.0)),
                ('reference_img', models.CharField(blank=True, max_length=200)),
                ('user_image', models.ImageField(blank=True, null=True, upload_to='scans/')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
