# Generated by Django 6.0.3 on 2026-04-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scannedspecimen',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Scanned Specimen', 'verbose_name_plural': 'Scanned Specimens'},
        ),
        migrations.AddField(
            model_name='scannedspecimen',
            name='entry_type',
            field=models.CharField(choices=[('VERIFIED', 'Herbarium Entry'), ('NEURAL', 'Neural Analysis Result')], default='NEURAL', max_length=10),
        ),
        migrations.AlterField(
            model_name='scannedspecimen',
            name='common_name',
            field=models.CharField(help_text='The primary name identified by Gemini (e.g., Tulsi)', max_length=200),
        ),
        migrations.AlterField(
            model_name='scannedspecimen',
            name='confidence',
            field=models.FloatField(default=0.0, help_text='AI confidence score from 0.0 to 100.0'),
        ),
        migrations.AlterField(
            model_name='scannedspecimen',
            name='reference_img',
            field=models.CharField(blank=True, max_length=200, verbose_name='Data Source Origin'),
        ),
        migrations.AlterField(
            model_name='scannedspecimen',
            name='scientific_name',
            field=models.CharField(blank=True, help_text='The botanical Latin name', max_length=200),
        ),
        migrations.AlterField(
            model_name='scannedspecimen',
            name='user_image',
            field=models.ImageField(blank=True, help_text='The original specimen photo uploaded by the developer', null=True, upload_to='scans/'),
        ),
    ]
