# Generated by Django 6.0.3 on 2026-04-14 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_scannedspecimen_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scannedspecimen',
            name='details',
            field=models.TextField(blank=True, help_text='AI analysis, manual notes, or search context related to this specimen.'),
        ),
        migrations.AlterField(
            model_name='scannedspecimen',
            name='entry_type',
            field=models.CharField(choices=[('VERIFIED', 'Herbarium Entry'), ('NEURAL', 'Neural Analysis Result'), ('SEARCH', 'Knowledge Search')], default='NEURAL', max_length=10),
        ),
    ]
