# Generated by Django 6.0.1 on 2026-04-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_scannedspecimen_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scannedspecimen',
            name='matched_image_url',
            field=models.URLField(blank=True, help_text='Reference image URL fetched from web search for this plant name.', null=True),
        ),
        migrations.AlterField(
            model_name='scannedspecimen',
            name='entry_type',
            field=models.CharField(choices=[('VERIFIED', 'Herbarium Entry'), ('NEURAL', 'AI Analysis Result'), ('SEARCH', 'Knowledge Search')], default='NEURAL', max_length=10),
        ),
    ]
